# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 09:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('config', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relative_index', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitness', models.DecimalField(decimal_places=16, max_digits=20)),
                ('rank', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neatweb.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_fitness', models.DecimalField(decimal_places=16, max_digits=20)),
                ('max_fitness', models.DecimalField(decimal_places=16, max_digits=20)),
                ('offspring', models.IntegerField()),
                ('age_since_imp', models.IntegerField()),
                ('generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neatweb.Generation')),
                ('population', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neatweb.Population')),
            ],
        ),
        migrations.AddField(
            model_name='generation',
            name='population',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='neatweb.Population'),
        ),
    ]
