# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 04:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neatweb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organism',
            name='generation',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='neatweb.Generation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organism',
            name='population',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='neatweb.Population'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organism',
            name='species',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='neatweb.Species'),
            preserve_default=False,
        ),
    ]
