# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neatweb', '0002_auto_20160306_0429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generation',
            old_name='relative_index',
            new_name='rel_index',
        ),
        migrations.AddField(
            model_name='organism',
            name='rel_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='organism',
            name='winner',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='population',
            name='rel_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='rel_index',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
