# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neatweb', '0003_auto_20160308_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='organism',
            name='marked',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='species',
            name='marked',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
