# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-08 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neatweb', '0005_organism_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organism',
            name='network',
            field=models.TextField(),
        ),
    ]
