# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 19:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neatweb', '0006_auto_20160308_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='jid',
            field=models.CharField(default='', max_length=37),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='experiment',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 13, 19, 49, 47, 742294)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organism',
            name='fitness',
            field=models.DecimalField(decimal_places=24, max_digits=32),
        ),
        migrations.AlterField(
            model_name='species',
            name='avg_fitness',
            field=models.DecimalField(decimal_places=24, max_digits=32),
        ),
        migrations.AlterField(
            model_name='species',
            name='max_fitness',
            field=models.DecimalField(decimal_places=24, max_digits=32),
        ),
    ]
