# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-03 16:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neatweb', '0007_auto_20160413_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='message',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='progress',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=5),
            preserve_default=False,
        ),
    ]
